# Generated by Django 6.0.4 on 2026-04-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0003_airplanetype_airline'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='airports.airline', verbose_name='Managed Airline'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='airports.airport', verbose_name='Managed Airport'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('airport_admin', 'Airport Admin'), ('airline_admin', 'Airline Admin'), ('system_admin', 'System Admin')], default='customer', max_length=20),
        ),
    ]
