# Generated by Django 6.0.4 on 2026-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('airport_admin', 'Airport Admin')], default='customer', max_length=20),
        ),
    ]
