version: "3.8"

services:
    airport_db_container:
        image: postgres:15
        container_name: airport_db_container
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        container_name: airport_redis_container
        restart: always
        ports:
            - "6379:6379"

    backend:
        build: .
        container_name: airport_backend_container
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - airport_db_container
            - redis

    celery:
        build: .
        container_name: airport_worker_container
        command: celery -A config worker -l INFO
        volumes:
            - .:/app
        env_file:
            - .env
        depends_on:
            - airport_db_container
            - redis
            - backend

volumes:
    postgres_data:
