# Generated by Django 6.0.4 on 2026-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
