# Generated by Django 6.0.4 on 2026-04-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='coef_business_class',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='flight',
            name='coef_first_class',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
    ]
