# Generated by Django 6.0.4 on 2026-04-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplanetype',
            name='business_class_rows',
            field=models.IntegerField(default=0, help_text='Number of rows starting from the front'),
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='first_class_rows',
            field=models.IntegerField(default=0),
        ),
    ]
