# Generated by Django 6.0.4 on 2026-04-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_airplanetype_business_class_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplanetype',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_airplane_types', to='airports.airline'),
        ),
    ]
