# Generated by Django 6.0.4 on 2026-04-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled by User'), ('refunded', 'Refunded'), ('expired', 'Expired (Timeout)'), ('completed', 'Completed (Flight Done)')], default='pending', max_length=20),
        ),
    ]
