# Generated by Django 6.0.4 on 2026-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('used', 'Used')], default='booked', max_length=20),
        ),
    ]
